version: 2

sources:
  - name: raw
    database: OLIST_DB
    schema: RAW
    tables:
      - name: RAW_CUSTOMERS
      - name: RAW_ORDERS
      - name: RAW_ORDER_ITEMS
      - name: RAW_ORDER_PAYMENTS
      - name: RAW_ORDER_REVIEWS
      - name: RAW_PRODUCTS
      - name: RAW_SELLERS
      - name: RAW_GEOLOCATION
      - name: RAW_CATEGORY_TRANSLATION